Repository casper-ecosystem/cep-78-enhanced-nft, pull requests merged in 2023-02, with the labels that each got.

#78 Issue sixty
  contract/src/constants.rs
  contract/src/error.rs
  contract/src/main.rs
  contract/src/modalities.rs
  contract/src/utils.rs
  rust-toolchain
  tests/src/burn.rs
  tests/src/metadata.rs
  tests/src/mint.rs
  tests/src/transfer.rs
  tests/src/upgrade.rs
  tests/src/utility/constants.rs
  tests/src/utility/installer_request_builder.rs
  tests/src/utility/support.rs
Labels: v1.2

#164 Add EventsMode modality
  Makefile
  README.md
  client/get_approved_session/src/main.rs
  client/mint_session/src/main.rs
  client/updated_receipts/README.md
  client/updated_receipts/src/main.rs
  contract/src/constants.rs
  contract/src/error.rs
  contract/src/events.rs
  contract/src/events/events_cep47.rs
  contract/src/events/events_ces.rs
  contract/src/lib.rs
  contract/src/main.rs
  contract/src/modalities.rs
  contract/src/utils.rs
  test-contracts/mangle_named_keys/src/main.rs
  test-contracts/minting_contract/src/main.rs
  tests/Cargo.toml
  tests/src/burn.rs
  tests/src/events.rs
  tests/src/installer.rs
  tests/src/lib.rs
  tests/src/metadata.rs
  tests/src/mint.rs
  tests/src/set_variables.rs
  tests/src/transfer.rs
  tests/src/upgrade.rs
  tests/src/utility/constants.rs
  tests/src/utility/installer_request_builder.rs
  tests/src/utility/support.rs
Labels: enhancement

#179 Set serde-json-wasm as dep
  client/updated_receipts/src/main.rs
  contract/Cargo.toml
  contract/src/main.rs
  contract/src/metadata.rs
  test-contracts/mangle_named_keys/src/main.rs
  test-contracts/minting_contract/src/main.rs
Labels: invalid

#170 Set TOKEN_ISSUERS entry to token minter instead of token owner
  contract/src/main.rs
  tests/src/mint.rs
Labels: bug
